### ISSUE TITLE
Random test failure with the scheduler

### ISSUE THREAD

**Issue by Thorinwasher** [MockBukkit/MockBukkit#1134]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest version of MockBukkit?

- [X] I am using the latest version of MockBukkit.

### Minecraft Version

1.21.1

### Describe the bug

I got this error when running all tests in mockbukkit. I think it is probability dependent or something as I have never seen this failure before, and this part of the code has not been touched.
```
BukkitSchedulerMockTest > longRunningTask_Throws_RunTimeException() FAILED
    org.opentest4j.AssertionFailedError at BukkitSchedulerMockTest.java:315
```

### Reproducible Test

Probability dependent

### Anything else?

Rerunning the test now succeeds

**Comment by 4everTheOne** [comment]
It also happened to me in the past. I think this may be related with concurrency, because i can reproduce it, if i comment out  this line:
https://github.com/MockBukkit/MockBukkit/blob/11ec9cabc7ef0788bf9f82fc7b30d6aea1a80838/src/main/java/be/seeseemelk/mockbukkit/scheduler/BukkitSchedulerMock.java#L487
I suspect that what is happening is: Main thread in being execute before the task is scheduled, and this results in the task not being active in pool yet, result in an assertion failure

**Comment by Thorinwasher** [comment]
I will just close this as completed with pr #1135 for now, hard to test if it fixed the issue though
