### ISSUE TITLE
PotionMetaMock causing compilation issues.

### ISSUE THREAD

**Issue by andrewkm** [MockBukkit/MockBukkit#1242]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest version of MockBukkit?

- [X] I am using the latest version of MockBukkit.

### Minecraft Version

1.21

### Describe the bug

Cannot compile v1.21
https://pastebin.com/raw/yyW6C1Ku

### Reproducible Test

Compile v1.21

**Comment by Thorinwasher** [comment]
This looks like an issue with using the wrong mockbukkit version against the wrong paper api version. You can either:
1. Exclude the paper api at test time (only possible when using gradle from what I know)
2. Find the correct matching paper api version. Note that this is sensitive to commits in the paper API; for example paper 1.21 has multiple iterations of its API.

Why is this necessary?

It's because mockbukkit is an alternative implementation of the paper API. We simply have the paper API as a dependency, which we then write our own alternative implementation. This will make the mockbukkit implementation sensitive to paper API version

**Comment by andrewkm** [comment]
Must be something to do with the recent paper hard fork / API it seems.
Was building just fine until recently. Hm.

**Comment by Thorinwasher** [comment]
The latest mockbukkit version is for the paper 1.21.3 api

**Comment by andrewkm** [comment]
> The latest mockbukkit version is for the paper 1.21.3 api

Ah alright thank you, guess I must've completely overlooked that. xD
