### ISSUE TITLE
Repository failed to be published on jitpack.io (and latest doesn't work with Gradle)

### ISSUE THREAD

**Issue by JacksonChen666** [MockBukkit/MockBukkit#130]
I've got errors reloading my Gradle project and checked on jitpack.io saying it's missing, and it seems like the build may have failed to be published (as the latest).

Failure log:
```
> Task :signMockBukkitPublication FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':signMockBukkitPublication'.
> Cannot perform signing task ':signMockBukkitPublication' because it has no configured signatory
```

Log: https://jitpack.io/com/github/seeseemelk/MockBukkit/v1.16-6672eca92e-1/build.log

**Comment by seeseemelk** [comment]
We're not really supporting Jitpack anymore. A new version gets published to Maven Central after every PR, although it can take a while before it gets properly indexed.

That said, the build error seems to be caused by our Gradle script attempting to sign the package when publishing to a local maven repository. There should be no reason for it to be doing that, so by fixing that issue Jitpack will most likely also be fixed.

**Comment by JacksonChen666** [comment]
So it seems like jitpack.io is not supported anymore, but the version can be changed to be the latest. Thank you for your help.

**Comment by seeseemelk** [comment]
I might still look into fixing the underlying build error, as it shouldn't fail. And that should fix Jitpack again, even if I don't really support it anymore.
