### ISSUE TITLE
Cannot initialize LibraryLoader due to missing dependency

### ISSUE THREAD

**Issue by TheBusyBiscuit** [MockBukkit/MockBukkit#214]
Using the latest version of `MockBukkit` (1.0.1) currently results in a lot of console spam.

```
May 24, 2021 5:39:22 PM org.bukkit.plugin.java.JavaPluginLoader <init>
WARN: Could not initialize LibraryLoader (missing dependencies?)
May 24, 2021 5:39:22 PM org.bukkit.plugin.java.JavaPluginLoader <init>
WARN: Could not initialize LibraryLoader (missing dependencies?)
May 24, 2021 5:39:22 PM org.bukkit.plugin.java.JavaPluginLoader <init>
WARN: Could not initialize LibraryLoader (missing dependencies?)
May 24, 2021 5:39:23 PM org.bukkit.plugin.java.JavaPluginLoader <init>
WARN: Could not initialize LibraryLoader (missing dependencies?)
```

This is due to the new `LibraryLoader` which was introduced to Bukkit here:
https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/commits/146a7e4bd764990c56bb326643e92eb69f24d27e

Particularly this section right here:
https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/browse/src/main/java/org/bukkit/plugin/java/LibraryLoader.java?at=146a7e4bd764990c56bb326643e92eb69f24d27e#51-70
It results in a `NoClassDefFoundError`. This is likely the result of `MockBukkit` not loading in the `org.eclipse.aether` dependency the `LibraryLoader` runs on.
We could add this dependency, however the `LibraryLoader` is package-private so we may need to deal with package-injecting some classes again here in the near future or/and start mocking this territory of Bukkit. As this is a very new addition to the Bukkit API, I am personally against it.

Since I don't wanna make this decision lightly, I decided to open an issue here.
To remind us to fix this at some point but also to see what others think about this problem.

Personal opinion: `JavaPluginLoader` should have an overloaded constructor or allow for library-loading to be disabled in general. I can assume not many servers liking this either. But here we are...

**Comment by zodiia** [comment]
My opinion is that it is an extremely useful new feature that will probably become the norm on a lot of plugins that don't want to support older versions.

In the post-1.17 world, Java 16 will be required on both clients and servers, which means goodbye Java 8 and its lack of modularity. In Java 8, using external libraries in .jar was easy, some reflections on the plugin's `URLClassLoader` and you were good to go. Something that wasn't possible since Java 9 and its modules. Of course, you could still shade your libraries onto your jar, but that is a pretty bad idea when you're using lots of differents libraries.

I personally already started using this new feature since the moment it came out, and reduced the .jar file size on my biggest project from 17MB to less than 1MB, which is a significant improvement, especially considering I would like to publish it on Spigot when it will be ready, and delivering 17MB jars is something you wouldn't want to do.

I will not support servers that would want to disable the `LibraryLoader` if it was a thing, because I'm not doing two separate jars that will do exactly the same thing. And, why would server owners want to disable it in the first place? It's not like they are not already at risk when downloading a plugin, either with shaded libraries or the code itself.

Concerning `MockBukkit`:
It unfortunately broke all my tests, as they no longer can load the plugins. I could not find any workaround, apart from switching to `1.16.4-R0.1-SNAPSHOT`, but I wouldn't want to do it.
I don't see the `LibraryLoader` being removed any time soon, and I think you should support it.

If you have any temporary workaround, I would very much appreciate if you could share it. As I said, switching versions is one, but not the prettiest (even if I don't think there are any API differences at all between 1.16.4 and 1.16.5)

**Comment by ItsLiyua** [comment]
How can I fix this? I'm pretty new to MockBukkit

**Comment by GeorgeV220** [comment]
> My opinion is that it is an extremely useful new feature that will probably become the norm on a lot of plugins that don't want to support older versions.
> 
> In the post-1.17 world, Java 16 will be required on both clients and servers, which means goodbye Java 8 and its lack of modularity. In Java 8, using external libraries in .jar was easy, some reflections on the plugin's `URLClassLoader` and you were good to go. Something that wasn't possible since Java 9 and its modules. Of course, you could still shade your libraries onto your jar, but that is a pretty bad idea when you're using lots of differents libraries.
> 
> I personally already started using this new feature since the moment it came out, and reduced the .jar file size on my biggest project from 17MB to less than 1MB, which is a significant improvement, especially considering I would like to publish it on Spigot when it will be ready, and delivering 17MB jars is something you wouldn't want to do.
> 
> I will not support servers that would want to disable the `LibraryLoader` if it was a thing, because I'm not doing two separate jars that will do exactly the same thing. And, why would server owners want to disable it in the first place? It's not like they are not already at risk when downloading a plugin, either with shaded libraries or the code itself.
> 
> Concerning `MockBukkit`:
> It unfortunately broke all my tests, as they no longer can load the plugins. I could not find any workaround, apart from switching to `1.16.4-R0.1-SNAPSHOT`, but I wouldn't want to do it.
> I don't see the `LibraryLoader` being removed any time soon, and I think you should support it.
> 
> If you have any temporary workaround, I would very much appreciate if you could share it. As I said, switching versions is one, but not the prettiest (even if I don't think there are any API differences at all between 1.16.4 and 1.16.5)

Check lucko's maven LibraryLoader, @Revxrsal fixed the issue and you can load libraries on runtime (Java 9+)
https://github.com/lucko/helper/commits/master/helper/src/main/java/me/lucko/helper/maven

**Comment by GeorgeV220** [comment]
> How can I fix this? I'm pretty new to MockBukkit

You can use paper/spigot below 1.16.5 until this is fixed by MockPlugin (or spigot ??)

**Comment by zodiia** [comment]
> Check lucko's maven LibraryLoader, @Revxrsal fixed the issue and you can load libraries on runtime (Java 9+)
> https://github.com/lucko/helper/commits/master/helper/src/main/java/me/lucko/helper/maven

I may be completely off track here, and if its the case, just ignore my comment.

Lucko's solution is to load their plugins via a jar-in-jar workaround. Basically the distributed plugins contains a .jar with the actual plugin and a bootstrapper that loads the .jar and the libraries all at once, via an additional `URLClassLoader`. It lets them load the libraries and the plugin at the same time in the same class loader (different from the one Spigot is providing), working around this issue completely.

**Comment by Narimm** [comment]
Why in gods name do we need to even mock jar loading...

This is a test bed - provide the dependencies as runtime in your build /test script  - and junit will dynamically make them available.  Unless someone can provide a use case that requires we actaully support using a LIbrary loader  - my advice is we ignore this - its not part of the Bukkit API.

I understand why Spigot thought it was a good idea...but its a broken implementation. Lucko's existing loader is a better idea.  MockBukkit doesn't need to support that.

Secondly given we will probably move from Spigot as per comments by Seeseemelk - I wouldnt even look at it until we support Paper.

**Comment by TheBusyBiscuit** [comment]
Since this discussion didn't really go anywhere, I am just going to do the naive approach I mentioned in the original post.
I will make a PR to add the dependencies for resolving maven dependencies.

> It results in a NoClassDefFoundError. This is likely the result of MockBukkit not loading in the org.eclipse.aether dependency the LibraryLoader runs on.
We could add this dependency, however the LibraryLoader is package-private so we may need to deal with package-injecting some classes again here in the near future or/and start mocking this territory of Bukkit. 

This will effectively disable the missing dependencies warning but the original concern that motivated this issue still stands. I guess time will show what side effects this will bring. But for now, I don't see anyone here suggesting a better alternative.

**Comment by seeseemelk** [comment]
> I guess time will show what side effects this will bring.

Ah, the tried and tested scream test. I like that idea!
