### ISSUE TITLE
EntityEquipment#getItem returns null

### ISSUE THREAD

**Issue by Narimm** [MockBukkit/MockBukkit#254]
Currently the bukkit API specifies that it is NOT NULL
https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/inventory/EntityEquipment.html#getItem(org.bukkit.inventory.EquipmentSlot)

However the Mock implementiation https://github.com/MockBukkit/MockBukkit/blob/8a6f913aa36336c118321ced0e6fdf1479cf2dfa/src/main/java/be/seeseemelk/mockbukkit/entity/EntityEquipmentMock.java#L73-L93

will return Null

I wasnt sure if CB still does this ?

The annotation would suggest it should return AIR

**Comment by seeseemelk** [comment]
The issues seems to be caused by some properties which are initialised to null.
https://github.com/MockBukkit/MockBukkit/blob/8a6f913aa36336c118321ced0e6fdf1479cf2dfa/src/main/java/be/seeseemelk/mockbukkit/entity/EntityEquipmentMock.java#L26-L32
If there were to be initialised to AIR instead it would probably work.
