### ISSUE TITLE
How to simulate a player disconnecting?

### ISSUE THREAD

**Issue by ItsLiyua** [MockBukkit/MockBukkit#302]
My question is quite simple. How can I simulate a player disconnecting?
There is no method called `quit()` or `disconnect()` in the `PlayerMock` class.

**Comment by ItsLiyua** [comment]
I just created an object of the `PlayerQuitEvent` and called it using `MockBukkit.getMock().getPluginManager().callEvent(event);`. That called my listener.

**Comment by seeseemelk** [comment]
I'm going to reopen this because it is a genuine missing feature.

Being able to call `disconnect()` on the PlayerMock class would be useful, as it not only needs to call an event, but also make sure that `Bukkit.getOnlinePlayers()` no longer return that player. And `Player.isOnline()` should return false instead of true after a call to `disconnect()`.

Additionally, it might be useful to have a function called `connect()` to simulate the player reconnecting.
For a reconnected player. `PlayerMock#hasPlayerBefore()` should return true.

**Comment by thelooter** [comment]
This should probably get the Enhancement Tag
